### PR TITLE
Update deprecated hook

### PR DESCRIPTION
**Pull request by TomAbel**
It seems this deprecated hook was overlooked and wasn't included in the last release. Adding it now as it doesn't modify existing functionality.

> REST API: Deprecates the wpcf7_ajax_json_echo and wpcf7_ajax_onload filter hooks and introduces the wpcf7_feedback_response and wpcf7_refill_response filter hooks as alternatives.
https://wordpress.org/plugins/contact-form-7/#developers

### CODE REVIEW

**Comment by kaittodesk** [comment]
Isn't the `wpcf7_ajax_json_echo` hook deprecated and `wpcf7_feedback_response` added from Contact Form 7 5.2? This plugin supports Contact Form 7 4.0+. Either we change the minimum requirement for CF7 to 5.2 or we need to support both hooks.

**Comment by TomAbel** [comment]
> Isn't the `wpcf7_ajax_json_echo` hook deprecated and `wpcf7_feedback_response` added from Contact Form 7 5.2? This plugin supports Contact Form 7 4.0+.
> 
> Either we change the minimum requirement for CF7 to 5.2 or we need to support both hooks.

Ah, my mistake. Didn't process this through in my head. Closing

**Comment by kaittodesk** [comment]
No need to close the PR. We would need to decide which route we are going to take, because at some point `wpcf7_ajax_json_echo` will stop working, because it is removed from CF7, and then this plugin will work only until certain CF7 versions.

According to WordPress.org plugin's statistics around ~55% of CF7 users have CF7 plugin installed with older version than 5.2. From that it would seem that supporting both hooks would make sense.

**Comment by TomAbel** [comment]
> No need to close the PR. We would need to decide which route we are going to take, because at some point `wpcf7_ajax_json_echo` will stop working, because it is removed from CF7, and then this plugin will work only until certain CF7 versions.
> 
> According to WordPress.org plugin's statistics around ~55% of CF7 users have CF7 plugin installed with older version than 5.2. From that it would seem that supporting both hooks would make sense.

Re-opened it and added the specified code to support both hooks. Please have a look.

**Review by kaittodesk — CHANGES_REQUESTED** [review]
Excellent! Just rename the fallback hook back to `wpcf7_ajax_json_echo`. At the moment fallback hooks to `wpcf7_feedback_response` as well.

**Review by kaittodesk — APPROVED** [review]

**Pull request merged**
